spring:
    datasource:
        #        url: jdbc:mysql://localhost:3305/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        #        username: root
        #        password: 1234
        url: jdbc:mysql://awseb-e-cefq7cz6vb-stack-awsebrdsdatabase-ol9k2ynbf4ki.cram6yk60opc.ap-northeast-2.rds.amazonaws.com/board?serverTimezone=Asia/Seoul
        username: sangwon
        password: h0t$ix19
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true # 쿼리 출력 여부
